defmodule Idealixir.Property do
  @derive [Poison.Encoder]
  defstruct address: "",
  bathrooms: 0,
  country: "es",
  distance: "",
  district: "",
  exterior: true,
  externalReference: "",
  floor: "",
  hasLift: true,
  hasVideo: true,
  latitude: 0,
  longitude: 0,
  municipality: "",
  neighborhood: "",
  newDevelopment: false,
  numPhotos: 0,
  operation: "",
  price: 0,
  priceByArea: 0,
  propertyCode: "",
  propertyType: "",
  province: "",
  rooms: 0,
  showAddress: false,
  size: 0,
  status: "",
  thumbnail: "",
  url: ""
end
